### ISSUE TITLE
incorrect delete[]

### ISSUE THREAD

**Issue by seanolly** [0816seung/cs4500a1part2#10]
https://github.com/0816seung/cs4500a1part2/blob/8647ef278dbeb618e950e1c6c09ac5f401bfea11/test-array.cpp#L21

this is an invalid delete, you need to call "delete" on allocated objects, and "delete[]" on actual arrays not the Array objects that we created.

**Comment by 0816seung** [comment]
I made the changes and pushed before I saw your PR but I merged it anyways.
