### ISSUE TITLE
Test Change Request

### ISSUE THREAD

**Issue by seanolly** [0816seung/cs4500a1part2#2]
Hi,
It looks like in the test file, that there is no cleanup procedure (no freeing of objects allocated on the heap). I suggest thinking about the array as a "view" over given elements, but without ownership of its elements. So this would mean deleting elements in the tests itself.
LMK what you think,
Sean

**Comment by 0816seung** [comment]
Your viewpoint makes sense. The elements should be deleted in the test itself rather than in the cleanup of the array. I will make updates to the tests shortly to add the deletions.
