### ISSUE TITLE
array clone

### ISSUE THREAD

**Issue by chris-gomes** [0816seung/cs4500a1part2#3]
It seems like your clone method in array.h returns a Object* type. It seems like it would make more sense for it to return an Array*, since it is making a copy of the array. If that is the case, can you push an update to correct this issue? Thank you!

**Comment by 0816seung** [comment]
We will change this shortly. It was originally set to return an Object* type to replicate Java functionality where all Objects inherit the clone method and maintain the same signature (the user would cast afterwards). Given the potential complications with casting, we'll change it to return an Array*.
